#!/usr/bin/env ruby
# This will generate a test suite.
# Stolen from digest-sha3-ruby

def test_case(length, bits, msg, md)
  puts <<-SHAVS_TEST_CASE
  // SHAVS #{bits} #{length} 
        inst = new SHA3.SHA3Hash(#{bits});
        inst.update(new Buffer(#{msg.inspect}, 'hex'));
        assert.equal(inst.digest('hex'), #{md.inspect});
        process.stdout.write(".");  
  SHAVS_TEST_CASE
end

puts <<-HEADER
// This file generated by generate_tests.rb

var assert = require('assert');
var SHA3 = require('./../build/Release/sha3');
var inst;  
HEADER

Dir[File.join('test', 'data', '*.rsp')].each do |rsp|
  length = bits = msg = md = nil
  open(rsp).each_line do |line|
    case line
    when /\[L = (\d+)\]/
      bits = Integer($1)
    when /Len = (\d+)/
      length = Integer($1)
    when /Msg = (\h+)/
      msg = $1.slice(0, 2*length/8)
    when /MD = (\h+)/
      md = $1.downcase
      test_case(length, bits, msg, md)
    end
  end # SHAV .rsp each_line
end # each SHAVS .rsp file

puts 'process.stdout.write("\\n");'
